# -  /SuhailTechInfo/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/Itxxwasi/tech /root/Itxxwasi
WORKDIR /root/Itxxwasi/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
  
# -  /SuhailTechInfo/ Don't change this name,



